name: Basic Variables Demo we are tesing

on:
  workflow_dispatch:

env:
 username1: uservalue1
 username2: "usernaem2"
  
jobs:
  job1:
    environment: test
    runs-on: ubuntu-latest
    outputs:
      var_output: ${{ steps.test.outputs.var_out }}
      direct_output: ${{ steps.test.outputs.direct_out }}
     
    steps:
      - name: Try all secret output methods
        id: test
        run: |
          # Step 1: secret into variable
          MY_SECRET="${{ secrets.SECRET1 }}"

          # Step 2: variable into GITHUB_OUTPUT
          echo "var_out=$MY_SECRET" >> $GITHUB_OUTPUT
          
          # Echo variable inside SAME job
          echo "job1 variable value: $MY_SECRET"
          
          # Step 3: direct secret into GITHUB_OUTPUT
          echo "direct_out=${{ secrets.SECRET1 }}" >> $GITHUB_OUTPUT

           # Echo direct secret inside SAME job
           echo "job1 direct secret: ${{ secrets.SECRET1 }}"

           echo "job1 direct secret: ${{username1}}"
           echo "job1 direct secret: $username1 "
           echo "job1 direct secret: ${username1:0:2}***"

           echo "job1 direct secret: ${{username2}}"
           echo "job1 direct secret: $username2 "
           echo "job1 direct secret: ${username2:0:2}***"


