name: Basic Variables Demo we are testing

on:
  workflow_dispatch:

env:
  username1: usernaem1
  username2: usernaem2

jobs:
  job1:
    environment: test
    runs-on: ubuntu-latest

    steps:
      - name: Try all variable methods
        run: |
          MY_SECRET="${{ secrets.SECRET1 }}"

          echo "---- SHELL VARIABLES ----"
          echo "username1 = $username1"
          echo "username2 = $username2"

          echo "masked secret = $MY_SECRET"
          echo "partial secret = ${MY_SECRET:0:2}***"

          echo "partial username1 = ${username1:0:2}***"
          echo "partial username2 = ${username2:0:2}***"

          echo "---- GITHUB EXPRESSIONS ----"
          echo "username1 = ${{ env.username1 }}"
          echo "username2 = ${{ env.username2 }}"
